version: '3.3'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
            - 80:80
        networks:
            - front-tier
        restart: always
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        networks:
            - front-tier
        restart: always
    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        volumes:
            - ./src/apache:/usr/local/apache2/htdocs/apache
        networks:
            - front-tier
        restart: always
    php56:
        depends_on:
            - reverseproxy
            - mysql
        image: php:5.6-apache
        volumes:
            - ./src/home:/var/www/html/home
        networks:
            - front-tier
            - back-tier
        restart: always
    php7:
        depends_on:
            - reverseproxy
            - mysql
        image: php:7.0-apache
        volumes:
            - ./src:/var/www/html
        networks:
            - front-tier
            - back-tier
        restart: always
    wordpress:
        image: wordpress:4.7.1-php7.0-fpm
        volumes:
            - ./src/wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=hugghugg
        depends_on:
            - reverseproxy
            - mysql
        networks:
            - front-tier
            - back-tier
        restart: always

    mysql:
        image: mariadb
        ports:
            - 3306:3306
        networks:
            - back-tier
        volumes:
            - ./tmp:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=hugghugg
        restart: always
networks:
  front-tier:
  back-tier:
