version: '3.3'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
            - 80:80
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        volumes:
            - ./src/apache:/usr/local/apache2/htdocs/apache
        restart: always
    php56:
        depends_on:
            - reverseproxy
        image: php:5.6-apache
        volumes:
            - ./src/home:/var/www/html/home
        restart: always
    php7:
        depends_on:
            - reverseproxy
        image: php:7.0-apache
        volumes:
            - ./src:/var/www/html
        restart: always
